name: CI

on:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Fetch repositories
        shell: bash
        env:
          TOKEN: ${{ secrets.ARTIFACT_HUB_TOKEN }}
          API_KEY: ${{ secrets.ARTIFACT_HUB_API_KEY_ID }}
          SECRET_KEY: ${{ secrets.ARTIFACT_HUB_API_SECRET_KEY }}
        run: |
          curl --fail -X GET "https://artifacthub.io/api/v1/repositories/helm" -H "accept: application/json" -H "X-API-KEY-ID: $API_KEY" -H "X-API-KEY-SECRET: $SECRET_KEY" -o repositories.json
      - name: Output repositories.json
        shell: bash
        run: |
          cat repositories.json
      - name: Upload repositories.json to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: repositories.json
          tag: latest
          overwrite: true
          file_glob: true
